### ISSUE TITLE
lora support, nice to have feature request

### ISSUE THREAD

**Issue by eugenioamato** [SethRobinson/aitools_client#10]
Any plan to support lora? 
(Or maybe I am unable to find how to use it)
off-topic, would be nice to have also a xyz matrix to explore all settings instead of only batch.
No way to set clip skip, eta and other params

**Comment by jonwong666** [comment]
Lora works fine for me, just add it to the prompt like you would normally in webui

eg: fancy pants frog <frog_01:1>
