### ISSUE TITLE
Feature Request: Support for ControlNet 1.1 models and preprocessors

### ISSUE THREAD

**Issue by aaronfang** [SethRobinson/aitools_client#12]
Thank you so much for making such a nice client tool that makes the interaction so much smoother!

I noticed that the current controlnet in img2img supports limited preprocessors and models, I did not find those models and preprocessors in controlnet1.1, such as lineart, reference_only, tile, etc. Probably it supported natively? Just filling in a cfg file will activate them? Also whether to support more than one controlnet? 

Hope my request is not too much. Thanks again for your work!

**Comment by SethRobinson** [comment]
Ok, these have been added.  Previously I had sort of hardcoded the preprocessors, it now properly will update as more are added by asking the server.
