### ISSUE TITLE
Error inpainting when no controlnet installed:  Index was outside the bounds of the array.TMPro.TMP_Text.DrawUnderlineMesh

### ISSUE THREAD

**Issue by eugenioamato** [SethRobinson/aitools_client#13]
Description:
Run automatic1111 or seth's ai server WITHOUT installing the sd-webui-controlNet plugin installed
Try to inpaint any image using the "!" exclamation mark button
Error:
The server doesn't start any generation, the log inside aitools_client shows:

<color=#ff8ff3ff>IndexOutOfRangeException: Index was outside the bounds of the array.TMPro.TMP_Text.DrawUnderlineMesh (UnityEngine.Vector3 start, UnityEngine.Vector3 end, System.Int32& index, System.Single startScale, System.Single endScale, System.Single maxScale, System.Single sdfScale, UnityEngine.Color32 underlineColor) (at ./Library/PackageCache/com.unity.textmeshpro@3.0.6/Scripts/Runtime/TMP_Text.cs:5750)
</color>
TMPro.TextMeshProUGUI.GenerateTextMesh () (at ./Library/PackageCache/com.unity.textmeshpro@3.0.6/Scripts/Runtime/TMPro_UGUI_Private.cs:4198)

note:
The normal generation (using the Generate button works correctly).

Expected behavior:
Should start inpaint, or manage the exception with error dialog and stopping generation animation (it actually shows "generating" and the stopwatch running even if it's not running anything, forever.)

Using aitools v0.74
Same behavior using normal automatic1111 and with aitools_server

**Comment by SethRobinson** [comment]
Hmm, I am not able to recreate the issue.  Is it a specific model, inpainting rect size, or imported image (with a weird size) that is causing it?  If you look at the server side, you might see a more useful error there.  As for the client, the built-in log goes apeshit sometimes when there are too many errors, although the log.txt it creates might be correct.

**Comment by eugenioamato** [comment]
No sorry, I have the same error on all checkpoints and all image sizes. Just reinstalled everything and the error is still there
The server has no error, the client is not sending anything
I don't know what log.txt you are talking about, no file is named like that.
I also can assure you that I can do generations and inpaints with the normal webui, but only the inpaint in your project fails.

Can you please share the previous versions of SethsAIToolsWindows.exe so I can check if it had it? I remember using it for inpaint successfully before last update.
Thanks

**Comment by eugenioamato** [comment]
I found a solution : 
    Assets\_Script\GameLogic.cs
    line 400
    
    public string GetCurrentControlNetPreprocessorString()
    {
        if (m_controlNetPreprocessorCurIndex>=m_controlNetPreprocessorArray.Count) {
            return "";
        }
        return m_controlNetPreprocessorArray[m_controlNetPreprocessorCurIndex];
    }
    
    For some reason, my controlNetPreprocessorArray is empty when I do the first inpaint, causing the aforementioned error. I never used controlNet, anyway, maybe it's missing somehow in my machine? 
Would be nice to know if any of the other user experienced my issue

**Comment by eugenioamato** [comment]
It's a pleasure. I love this project very much, so I also installed unity and I can now surf your project and refresh my C#, that I abandoned 5-6 years ago.
