### ISSUE TITLE
AI paintball not working - Passed in texture is invalid (null)

### ISSUE THREAD

**Issue by eugenioamato** [SethRobinson/aitools_client#14]
Description:
Opening the AI Paintball game does not generate any image. 
Error:
The log is flooded with this errors:

1:

<color=#ff8ff3ff>ArgumentException: Passed in texture is invalid (null).GamePicManager.BuildJSonRequestForInpaint (System.String prompt, System.String negativePrompt, UnityEngine.Texture2D pic512, UnityEngine.Texture2D mask512, System.Boolean bRemoveBackground, System.Boolean bOperateOnSubjectOnly, System.Boolean bDisableTranslucencyOfMask, System.Boolean bReverseSubjectMask, System.Boolean bUseControlNet) (at C:/code/aitools_client/Assets/_Script/GamePicManager.cs:34)
</color>
ShootingGalleryLogic.Update () (at C:/code/aitools_client/Assets/Experiments/ShootingGallery/ShootingGalleryLogic.cs:355)

2:
<color=#ff8ff3ff>ArgumentException: Passed in texture is invalid (null).GamePicManager.BuildJSonRequestForInpaint (System.String prompt, System.String negativePrompt, UnityEngine.Texture2D pic512, UnityEngine.Texture2D mask512, System.Boolean bRemoveBackground, System.Boolean bOperateOnSubjectOnly, System.Boolean bDisableTranslucencyOfMask, System.Boolean bReverseSubjectMask, System.Boolean bUseControlNet) (at C:/code/aitools_client/Assets/_Script/GamePicManager.cs:34)
</color>
ShootingGalleryLogic.Update () (at C:/code/aitools_client/Assets/Experiments/ShootingGallery/ShootingGalleryLogic.cs:341)

Expected behavior:
Should start generating friend/enemy images

Using v.0.74
the controlNet plugin is installed
Bug appearing using both automatic1111 and seth's ai server

**Comment by SethRobinson** [comment]
Hrm.  I tested with and without ControlNet enabled and both work ok here - there must be something else different in our settings.  Does the "pizza" example work?

**Comment by eugenioamato** [comment]
yes all other experiments work fine

**Comment by eugenioamato** [comment]
The bug disappeared, I have no clue why, it works perfectly

**Comment by SethRobinson** [comment]
I think this might be due to what seems to be a controlnet or auto1111 API bug - after using ControlNet, any feature that DOESN'T use controlnet will start sending errors until the server is restarted or a new model is reloaded.  (controlnet never turns itself off properly) Still looking into it.

**Comment by SethRobinson** [comment]
Latest version of ControlNet has fixed this issue, closing again!
