### ISSUE TITLE
ERRORs: new Texture2D(0, 0, TextureFormat.RGBA32, false) because of Unity API changes

### ISSUE THREAD

**Issue by Martin80** [SethRobinson/aitools_client#15]
With newer Unity versions (f.e.2023.1.20f) it seems texture size of 0,0 is not allowed anymore?! A quick fix is to change all scripts from texture size 0,0 to 1,1
 
from:  Texture2D texture = new Texture2D(0, 0, TextureFormat.RGBA32, false);
to:      Texture2D texture = new Texture2D(1, 1, TextureFormat.RGBA32, false);

Error messages:

Cannot initialize non-default texture with negative or zero width.
UnityEngine.Texture2D:.ctor (int,int,UnityEngine.TextureFormat,bool)
PicTextToImage/<GetRequest>d__28:MoveNext () (at Assets/_Script/Pic/PicTextToImage.cs:288)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

UnityException: Failed to create texture because of invalid parameters.
UnityEngine.Texture2D.Internal_Create (UnityEngine.Texture2D mono, System.Int32 w, System.Int32 h, System.Int32 mipCount, UnityEngine.Experimental.Rendering.GraphicsFormat format, UnityEngine.TextureColorSpace colorSpace, UnityEngine.Experimental.Rendering.TextureCreationFlags flags, System.IntPtr nativeTex, System.String mipmapLimitGroupName) (at <36128ec596ab42c8af4441b8e0cdd33a>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height, UnityEngine.TextureFormat textureFormat, System.Int32 mipCount, System.Boolean linear, System.IntPtr nativeTex, System.Boolean createUninitialized, System.Boolean ignoreMipmapLimit, System.String mipmapLimitGroupName) (at <36128ec596ab42c8af4441b8e0cdd33a>:0)
UnityEngine.Texture2D..ctor (System.Int32 width, System.Int32 height, UnityEngine.TextureFormat textureFormat, System.Boolean mipChain) (at <36128ec596ab42c8af4441b8e0cdd33a>:0)
PicTextToImage+<GetRequest>d__28.MoveNext () (at Assets/_Script/Pic/PicTextToImage.cs:288)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <36128ec596ab42c8af4441b8e0cdd33a>:0)

**Comment by SethRobinson** [comment]
Ah, thanks for the heads-ups and fix.
