### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by jonwong666** [SethRobinson/aitools_client#6]
Hi Seth, the crazy cam feature is really cool, as a artist I am exploring collaborative paintings with AI, and I would like to use this to create interesting images & videos from actual paintings I create live on webcam.
Could I request a few features added to crazy cam :)
- update time [secs] // this would control how frequent the SD and webcam image is updated, a cool down timer
- pause / freeze // pause or freeze current frame / updates 
- set image size // instead of square ratio a custom output size ( or use same as the main settings )
- save generated images to autosave

thanks!

**Comment by filliptm** [comment]
Bump, Keep developing this feature, the crazy cam feature is so sick! im going to be incorporating it into live installations. The more features the better!

**Comment by jonwong666** [comment]
thank you! it would also be great if we could minimize the grey status box to free up screen real estate please

**Comment by jonwong666** [comment]
seed box appears to revert back to 0 after inputting -1, not sure if its just the text box or effecting the actual seed

**Comment by SethRobinson** [comment]
Ok, please try the latest version - I added everything except the set image size feature, that's sort of complicated to do right

**Comment by jonwong666** [comment]
hi Seth, thank you so much for taking a look at my requests! I tested the new version and its running great.
One request regarding "hideGui" is it possible to hide the textbox on the bottom as well?
![image](https://user-images.githubusercontent.com/41051927/236886426-4b519036-7519-4e56-a4a1-2b99daf9ade1.png)

Also regarding image size, it would be great if this could be updated in the future, most of my LORAs have been trained on portrait images, so they tend to work better at 512x704.

I will test the new controlnet 1.1 and let you know how it goes also.

thanks again! :)

**Comment by SethRobinson** [comment]
Correction to above - the hotkey to toggle the log is Shift-`  (shift-backtick).  Ctrl key not needed.

**Comment by jonwong666** [comment]
perfect thanks!
![image](https://user-images.githubusercontent.com/41051927/236929531-41a29b59-96fa-441f-9bbe-0e02a47bfb40.png)
