### ISSUE TITLE
feature request: HighRes.fix (latent upscale)

### ISSUE THREAD

**Issue by Martin80** [SethRobinson/aitools_client#7]
First of all, thank you for sharing this great sd unity implementation! I really enjoy it!

How could the feature "HighRes.fix" (latend upscale) be used inside aitools_client? 

If this feature is activated in the webUi  f.e. with upscale=2 and DenoisingStrength=0.5 the upscale is not done after the generation, but while or before generation process completes (latent upscale), and it gives very nice and fast results which then can be upscaled even higher but with much more detail.

**Comment by SethRobinson** [comment]
Thanks, I'll verify that it's something I can enable via auto1111's API and add it if possible!

**Comment by Martin80** [comment]
Sounds great (I keep my fingers crossed)! Thank you!

May I ask you if this is the right place ("PicUpscale.cs" > ""upscaler_1"": ....) to change the upscale model?  


        string json =
 $@"{{
           
            ""image"": ""{imgBase64}"",
            ""upscaling_resize"": 2,
             ""upscaler_1"": ""SwinIR_4x"",
             ""upscaler_2"": ""ESRGAN_4x"",
             ""extras_upscaler_2_visibility:"": 1,
            ""gfpgan_visibility"": {gfpgan_visibility},
            ""codeformer_visibility"": {codeformer_visibility},
             ""codeformer_weight"": 0,
             ""upscale_first"": true

**Comment by SethRobinson** [comment]
Yep - that controls what is used when upscale option (that is applied to existing images) is used.  (the Process->Upscale 2X option, U icon, or Upscale checkmark, they all run that)

**Comment by Martin80** [comment]
Thank you so much, it works great.

The other improvements (crazy cam, upscale fix, etc) of v0.73 are also very welcome.
